---
version: "3.7"

services:
  traefik:
    image: traefik:v2.5
    networks:
      ocis-net:
        aliases:
          - ${OCIS_DOMAIN:-ocis.owncloud.test}
    command:
      - "--log.level=${TRAEFIK_LOG_LEVEL:-ERROR}"
      # letsencrypt configuration
      - "--certificatesResolvers.http.acme.email=${TRAEFIK_ACME_MAIL:-example@example.org}"
      - "--certificatesResolvers.http.acme.storage=/certs/acme.json"
      - "--certificatesResolvers.http.acme.httpChallenge.entryPoint=http"
      # enable dashboard
      - "--api.dashboard=true"
      # define entrypoints
      - "--entryPoints.http.address=:80"
      - "--entryPoints.http.http.redirections.entryPoint.to=https"
      - "--entryPoints.http.http.redirections.entryPoint.scheme=https"
      - "--entryPoints.https.address=:443"
      # docker provider (get configuration from container labels)
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedByDefault=false"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "certs:/certs"
    labels:
      - "traefik.enable=${TRAEFIK_DASHBOARD:-false}"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_BASIC_AUTH_USERS:-admin:$$apr1$$4vqie50r$$YQAmQdtmz5n9rEALhxJ4l.}" # defaults to admin:admin
      - "traefik.http.routers.traefik.entrypoints=https"
      - "traefik.http.routers.traefik.rule=Host(`${TRAEFIK_DOMAIN:-traefik.owncloud.test}`)"
      - "traefik.http.routers.traefik.middlewares=traefik-auth"
      - "traefik.http.routers.traefik.tls.certresolver=http"
      - "traefik.http.routers.traefik.service=api@internal"
    logging:
      driver: "local"
    restart: always

  ocis-1:
    image: owncloud/ocis:${OCIS_1_DOCKER_TAG:-latest}
    networks:
      ocis-net:
    entrypoint:
      - /bin/sh
      - /entrypoint-override.sh
    environment:
      OCIS_URL: https://${OCIS_1_DOMAIN:-ocis-1.owncloud.test}
      OCIS_LOG_LEVEL: ${OCIS_1_LOG_LEVEL:-error} # make oCIS less verbose
      PROXY_TLS: "false" # do not use SSL between Traefik and oCIS
      # change default secrets
      IDP_LDAP_BIND_PASSWORD: ${IDP_1_LDAP_BIND_PASSWORD:-idp-1}
      STORAGE_LDAP_BIND_PASSWORD: ${STORAGE_1_LDAP_BIND_PASSWORD:-reva-1}
      OCIS_JWT_SECRET: ${OCIS_1_JWT_SECRET:-Pive-Fumkiu4-1}
      STORAGE_TRANSFER_SECRET: ${STORAGE_1_TRANSFER_SECRET:-replace-me-with-a-transfer-secret-1}
      OCIS_MACHINE_AUTH_API_KEY: ${OCIS_1_MACHINE_AUTH_API_KEY:-change-me-please-1}
      # INSECURE: needed if oCIS / Traefik is using self generated certificates
      OCIS_INSECURE: "${INSECURE:-false}"
    volumes:
      - ./config/ocis/entrypoint-override.sh:/entrypoint-override.sh
      - ocis-data-1:/var/lib/ocis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ocis.entrypoints=https"
      - "traefik.http.routers.ocis.rule=Host(`${OCIS_1_DOMAIN:-ocis-1.owncloud.test}`)"
      - "traefik.http.routers.ocis.tls.certresolver=http"
      - "traefik.http.routers.ocis.service=ocis-1"
      - "traefik.http.services.ocis.loadbalancer.server.port=9200"
    logging:
      driver: "local"
    restart: always

  ocis-2:
    image: owncloud/ocis:${OCIS_2_DOCKER_TAG:-latest}
    networks:
      ocis-net:
    entrypoint:
      - /bin/sh
      - /entrypoint-override.sh
    environment:
      OCIS_URL: https://${OCIS_2_DOMAIN:-ocis-2.owncloud.test}
      OCIS_LOG_LEVEL: ${OCIS_2_LOG_LEVEL:-error} # make oCIS less verbose
      PROXY_TLS: "false" # do not use SSL between Traefik and oCIS
      # change default secrets
      IDP_LDAP_BIND_PASSWORD: ${IDP_2_LDAP_BIND_PASSWORD:-idp-2}
      STORAGE_LDAP_BIND_PASSWORD: ${STORAGE_2_LDAP_BIND_PASSWORD:-reva-2}
      OCIS_JWT_SECRET: ${OCIS_2_JWT_SECRET:-Pive-Fumkiu4-2}
      STORAGE_TRANSFER_SECRET: ${STORAGE_2_TRANSFER_SECRET:-replace-me-with-a-transfer-secret-2}
      OCIS_MACHINE_AUTH_API_KEY: ${OCIS_2_MACHINE_AUTH_API_KEY:-change-me-please-2}
      # INSECURE: needed if oCIS / Traefik is using self generated certificates
      OCIS_INSECURE: "${INSECURE:-false}"
    volumes:
      - ./config/ocis/entrypoint-override.sh:/entrypoint-override.sh
      - ocis-data-2:/var/lib/ocis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ocis.entrypoints=https"
      - "traefik.http.routers.ocis.rule=Host(`${OCIS_2_DOMAIN:-ocis-1.owncloud.test}`)"
      - "traefik.http.routers.ocis.tls.certresolver=http"
      - "traefik.http.routers.ocis.service=ocis-2"
      - "traefik.http.services.ocis.loadbalancer.server.port=9200"
    logging:
      driver: "local"
    restart: always

volumes:
  certs:
  ocis-data-1:
  ocis-data-2:

networks:
  ocis-net:
