---
version: "3.7"

services:
  traefik:
    networks:
      ocis-net:
        aliases:
          - ${OCIS_DOMAIN:-ocis.owncloud.test}
    depends_on:
      - web
    extends:
        file: docker-compose.base.yml
        service: traefik

  ocis:
    networks:
      ocis-int:
        aliases:
          - idp.owncloud.test
          - storage-frontend.owncloud.test
          - storage-gateway.owncloud.test
          - ocs.owncloud.test
          - accounts.owncloud.test
          - settings.owncloud.test
          - webdav.owncloud.test
    extends:
        file: docker-compose.base.yml
        service: ocis
    environment:
      OCIS_RUN_EXTENSIONS: accounts, glauth, idp, settings, ocs, storage-appprovider, storage-authbasic, storage-authbearer, storage-authmachine, storage-frontend, storage-gateway, storage-groupprovider, storage-metadata, storage-public-link, storage-shares, storage-sharing, storage-userprovider, storage-users, store, thumbnails, webdav
      OCIS_COMMAND: server
      IDP_HTTP_ADDR: 0.0.0.0:9130
      OCS_HTTP_ADDR: 0.0.0.0:9110
      WEBDAV_HTTP_ADDR: 0.0.0.0:9115
      ACCOUNTS_HTTP_ADDR: 0.0.0.0:9181
      ACCOUNTS_GRPC_ADDR: 0.0.0.0:9180
      STORAGE_FRONTEND_HTTP_ADDR: 0.0.0.0:9140
      STORAGE_GATEWAY_GRPC_ADDR: 0.0.0.0:9142
      REVA_GATEWAY: 0.0.0.0:9142
      SETTINGS_HTTP_ADDR: 0.0.0.0:9190
      SETTINGS_GRPC_ADDR: 0.0.0.0:9191
      STORAGE_METADATA_GRPC_PROVIDER_ADDR: 0.0.0.0:9215
      STORAGE_METADATA_HTTP_ADDR: 0.0.0.0:9216

      # required for file uploading
      STORAGE_FRONTEND_PUBLIC_URL: http://${OCIS_DOMAIN:-ocis.owncloud.test}:9140
    ports:
      - 9130:9130
      - 9110:9110
      - 9115:9115
      - 9180:9180
      - 9181:9181
      - 9190:9190
      - 9191:9191
      - 9215:9215
      - 9216:9216
      - 9142:9142

  proxy:
    extends:
        file: docker-compose.base.yml
        service: ocis
    networks:
      ocis-int:
        aliases:
          - internal.owncloud.test
      ocis-net:
    depends_on:
      - ocis
      - web
    environment:
      OCIS_RUN_EXTENSIONS: proxy
      OCIS_COMMAND: server
      PROXY_TLS: false
      PROXY_CONFIG_FILE: /etc/ocis/proxy.json
      PROXY_HTTP_ADDR: 0.0.0.0:9200
      REVA_GATEWAY: storage-gateway.owncloud.test:9142 # has an issue with webdav HERE
    entrypoint:
      - /bin/sh
      - /entrypoint-override.sh
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.proxy.entrypoints=https"
      # maps based on domain from https --> ocis.owncloud.test:9200
      - "traefik.http.routers.proxy.rule=Host(`${OCIS_DOMAIN:-ocis.owncloud.test}`)"
      - "traefik.http.routers.proxy.tls.certresolver=http"
      - "traefik.http.routers.proxy.service=proxy"
      - "traefik.http.services.proxy.loadbalancer.server.port=9200"
      # IMPORTANT - otherwise it will bind to "ocis-int" (although it should not be able to)
      - "traefik.docker.network=${COMPOSE_PROJECT_NAME}_ocis-net"
    ports:
      - 9140:9140


  web:
    depends_on:
      - ocis
    extends:
        file: docker-compose.base.yml
        service: ocis
    networks:
      ocis-int:
        aliases:
          - web.owncloud.test
    environment:
      OCIS_RUN_EXTENSIONS: web
      OCIS_COMMAND: server
      WEB_HTTP_ADDR: web.owncloud.test:9100
      WEB_UI_CONFIG: /etc/ocis/config.json
    entrypoint:
      - /bin/sh
      - /entrypoint-override.sh
    ports:
      - 9100:9100

  graph:
    depends_on:
      - ocis
    extends:
        file: docker-compose.base.yml
        service: ocis
    networks:
      ocis-int:
        aliases:
          - graph.owncloud.test
    environment:
      OCIS_RUN_EXTENSIONS: graph
      OCIS_COMMAND: server
      GRAPH_HTTP_ADDR: graph.owncloud.test:9120
    entrypoint:
      - /bin/sh
      - /entrypoint-override.sh
    ports:
      - 9120:9120

  graph-explorer:
    depends_on:
      - ocis
    extends:
        file: docker-compose.base.yml
        service: ocis
    networks:
      ocis-int:
        aliases:
          - graph-explorer.owncloud.test
    environment:
      OCIS_RUN_EXTENSIONS: graph-explorer
      OCIS_COMMAND: server
      GRAPH_EXPLORER_HTTP_ADDR: graph-explorer.owncloud.test:9135
    entrypoint:
      - /bin/sh
      - /entrypoint-override.sh
    ports:
      - 9135:9135

volumes:
  certs:
  ocis-data:

networks:
  ocis-net:
    ipam:
      config:
        - subnet: 172.177.0.0/16
  ocis-int:
    ipam:
      config:
        - subnet: 10.103.0.1/16
