with-expecter: true
filename: "{{.InterfaceName | snakecase }}.go"
dir: "{{.PackageName}}/mocks"
mockname: "{{.InterfaceName}}"
outpkg: "mocks"
packages:
    github.com/go-ldap/ldap/v3:
        interfaces:
            Client:
                config:
                    dir: mocks
                    filename: ldapclient.go